package logistics;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

/**
 * Servlet implementation class Bill
 */
public class appointmentslip extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public appointmentslip() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		HttpSession session = request.getSession();
		String sid = (String)session.getAttribute("attributeName");
		String search = sid;
		System.out.println("Search session: "+search);
		response.setContentType("text/html");
		PrintWriter out = response.getWriter();
		
		String sqid=null;
		String sqname=null;
		String total = null;
		try {
			Class.forName("com.mysql.cj.jdbc.Driver");
			String url1 = "jdbc:mysql://localhost:3306/healthcareproject";
			String username1 = "root";
			String pass1 = "20csu214";
			
			Date d = new Date();
			Connection con = DriverManager.getConnection(url1, username1, pass1);
			
			String query = "select name,timings from appoint";
			Statement pstmt = con.createStatement();
			ResultSet rs = pstmt.executeQuery(query);
			out.println("<!DOCTYPE html>\r\n"
					+ "<!-- Designined by CodingLab | www.youtube.com/codinglabyt -->\r\n"
					+ "<html lang=\"en\" dir=\"ltr\">\r\n"
					+ "  <head>\r\n"
					+ "  <style>\r\n"
					+ "  .invoice-box {\r\n"
					+ "				max-width: 800px;\r\n"
					+ "				margin: auto;\r\n"
					+ "				padding: 30px;\r\n"
					+ "				border: 1px solid #eee;\r\n"
					+ "				box-shadow: 0 0 10px rgba(0, 0, 0, 0.15);\r\n"
					+ "				font-size: 16px;\r\n"
					+ "				line-height: 24px;\r\n"
					+ "				font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;\r\n"
					+ "				color: #555;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.invoice-box table {\r\n"
					+ "				width: 100%;\r\n"
					+ "				line-height: inherit;\r\n"
					+ "				text-align: left;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.invoice-box table td {\r\n"
					+ "				padding: 5px;\r\n"
					+ "				vertical-align: top;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.invoice-box table tr td:nth-child(2) {\r\n"
					+ "				text-align: right;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.invoice-box table tr.top table td {\r\n"
					+ "				padding-bottom: 20px;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.invoice-box table tr.top table td.title {\r\n"
					+ "				font-size: 45px;\r\n"
					+ "				line-height: 45px;\r\n"
					+ "				color: #333;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.invoice-box table tr.information table td {\r\n"
					+ "				padding-bottom: 40px;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.invoice-box table tr.heading td {\r\n"
					+ "				background: #eee;\r\n"
					+ "				border-bottom: 1px solid #ddd;\r\n"
					+ "				font-weight: bold;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.invoice-box table tr.details td {\r\n"
					+ "				padding-bottom: 20px;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.invoice-box table tr.item td {\r\n"
					+ "				border-bottom: 1px solid #eee;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.invoice-box table tr.item.last td {\r\n"
					+ "				border-bottom: none;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.invoice-box table tr.total td:nth-child(2) {\r\n"
					+ "				border-top: 2px solid #eee;\r\n"
					+ "				font-weight: bold;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			@media only screen and (max-width: 600px) {\r\n"
					+ "				.invoice-box table tr.top table td {\r\n"
					+ "					width: 100%;\r\n"
					+ "					display: block;\r\n"
					+ "					text-align: center;\r\n"
					+ "				}\r\n"
					+ "\r\n"
					+ "				.invoice-box table tr.information table td {\r\n"
					+ "					width: 100%;\r\n"
					+ "					display: block;\r\n"
					+ "					text-align: center;\r\n"
					+ "				}\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			/** RTL **/\r\n"
					+ "			.invoice-box.rtl {\r\n"
					+ "				direction: rtl;\r\n"
					+ "				font-family: Tahoma, 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.invoice-box.rtl table {\r\n"
					+ "				text-align: right;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.invoice-box.rtl table tr td:nth-child(2) {\r\n"
					+ "				text-align: left;\r\n"
					+ "			}\r\n"
					+ "  /* Googlefont Poppins CDN Link */\r\n"
					+ "@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');\r\n"
					+ "*{\r\n"
					+ "  margin: 0;\r\n"
					+ "  padding: 0;\r\n"
					+ "  box-sizing: border-box;\r\n"
					+ "  font-family: 'Poppins', sans-serif;\r\n"
					+ "}\r\n"
					+ ".sidebar{\r\n"
					+ "  position: fixed;\r\n"
					+ "  height: 100%;\r\n"
					+ "  width: 240px;\r\n"
					+ "  background: #289d75;\r\n"
					+ "  transition: all 0.5s ease;\r\n"
					+ "}\r\n"
					+ ".sidebar.active{\r\n"
					+ "  width: 60px;\r\n"
					+ "}\r\n"
					+ ".sidebar .logo-details{\r\n"
					+ "  height: 80px;\r\n"
					+ "  display: flex;\r\n"
					+ "  align-items: center;\r\n"
					+ "}\r\n"
					+ ".sidebar .logo-details i{\r\n"
					+ "  font-size: 28px;\r\n"
					+ "  font-weight: 500;\r\n"
					+ "  color: #fff;\r\n"
					+ "  min-width: 60px;\r\n"
					+ "  text-align: center\r\n"
					+ "}\r\n"
					+ ".sidebar .logo-details .logo_name{\r\n"
					+ "  color: #fff;\r\n"
					+ "  font-size: 24px;\r\n"
					+ "  font-weight: 500;\r\n"
					+ "}\r\n"
					+ ".sidebar .nav-links{\r\n"
					+ "  margin-top: 10px;\r\n"
					+ "}\r\n"
					+ ".sidebar .nav-links li{\r\n"
					+ "  position: relative;\r\n"
					+ "  list-style: none;\r\n"
					+ "  height: 50px;\r\n"
					+ "}\r\n"
					+ ".sidebar .nav-links li a{\r\n"
					+ "  height: 100%;\r\n"
					+ "  width: 100%;\r\n"
					+ "  display: flex;\r\n"
					+ "  align-items: center;\r\n"
					+ "  text-decoration: none;\r\n"
					+ "  transition: all 0.4s ease;\r\n"
					+ "}\r\n"
					+ ".sidebar .nav-links li a.active{\r\n"
					+ "  background:#08563c;\r\n"
					+ "}\r\n"
					+ ".sidebar .nav-links li a:hover{\r\n"
					+ "  background: #08563c;\r\n"
					+ "}\r\n"
					+ ".sidebar .nav-links li i{\r\n"
					+ "  min-width: 60px;\r\n"
					+ "  text-align: center;\r\n"
					+ "  font-size: 18px;\r\n"
					+ "  color: #fff;\r\n"
					+ "}\r\n"
					+ ".sidebar .nav-links li a .links_name{\r\n"
					+ "  color: #fff;\r\n"
					+ "  font-size: 15px;\r\n"
					+ "  font-weight: 400;\r\n"
					+ "  white-space: nowrap;\r\n"
					+ "}\r\n"
					+ ".sidebar .nav-links .log_out{\r\n"
					+ "  position: absolute;\r\n"
					+ "  bottom: 0;\r\n"
					+ "  width: 100%;\r\n"
					+ "}\r\n"
					+ ".home-section{\r\n"
					+ "  position: relative;\r\n"
					+ "  background: #f5f5f5;\r\n"
					+ "  min-height: 100vh;\r\n"
					+ "  width: calc(100% - 240px);\r\n"
					+ "  left: 240px;\r\n"
					+ "  transition: all 0.5s ease;\r\n"
					+ "}\r\n"
					+ ".sidebar.active ~ .home-section{\r\n"
					+ "  width: calc(100% - 60px);\r\n"
					+ "  left: 60px;\r\n"
					+ "}\r\n"
					+ ".home-section nav{\r\n"
					+ "  display: flex;\r\n"
					+ "  justify-content: space-between;\r\n"
					+ "  height: 80px;\r\n"
					+ "  background: #fff;\r\n"
					+ "  display: flex;\r\n"
					+ "  align-items: center;\r\n"
					+ "  position: fixed;\r\n"
					+ "  width: calc(100% - 240px);\r\n"
					+ "  left: 240px;\r\n"
					+ "  z-index: 100;\r\n"
					+ "  padding: 0 20px;\r\n"
					+ "  box-shadow: 0 1px 1px rgba(0, 0, 0, 0.1);\r\n"
					+ "  transition: all 0.5s ease;\r\n"
					+ "}\r\n"
					+ ".sidebar.active ~ .home-section nav{\r\n"
					+ "  left: 60px;\r\n"
					+ "  width: calc(100% - 60px);\r\n"
					+ "}\r\n"
					+ ".home-section nav .sidebar-button{\r\n"
					+ "  display: flex;\r\n"
					+ "  align-items: center;\r\n"
					+ "  font-size: 24px;\r\n"
					+ "  font-weight: 500;\r\n"
					+ "}\r\n"
					+ "nav .sidebar-button i{\r\n"
					+ "  font-size: 35px;\r\n"
					+ "  margin-right: 10px;\r\n"
					+ "}\r\n"
					+ ".home-section nav .search-box{\r\n"
					+ "  position: relative;\r\n"
					+ "  height: 50px;\r\n"
					+ "  max-width: 550px;\r\n"
					+ "  width: 100%;\r\n"
					+ "  margin: 0 20px;\r\n"
					+ "}\r\n"
					+ "nav .search-box input{\r\n"
					+ "  height: 100%;\r\n"
					+ "  width: 100%;\r\n"
					+ "  outline: none;\r\n"
					+ "  background: #F5F6FA;\r\n"
					+ "  border: 2px solid #EFEEF1;\r\n"
					+ "  border-radius: 6px;\r\n"
					+ "  font-size: 18px;\r\n"
					+ "  padding: 0 15px;\r\n"
					+ "}\r\n"
					+ "nav .search-box .bx-search{\r\n"
					+ "  position: absolute;\r\n"
					+ "  height: 40px;\r\n"
					+ "  width: 40px;\r\n"
					+ "  background: #2697FF;\r\n"
					+ "  right: 5px;\r\n"
					+ "  top: 50%;\r\n"
					+ "  transform: translateY(-50%);\r\n"
					+ "  border-radius: 4px;\r\n"
					+ "  line-height: 40px;\r\n"
					+ "  text-align: center;\r\n"
					+ "  color: #fff;\r\n"
					+ "  font-size: 22px;\r\n"
					+ "  transition: all 0.4 ease;\r\n"
					+ "}\r\n"
					+ ".home-section nav .profile-details{\r\n"
					+ "  display: flex;\r\n"
					+ "  align-items: center;\r\n"
					+ "  background: #F5F6FA;\r\n"
					+ "  border: 2px solid #EFEEF1;\r\n"
					+ "  border-radius: 6px;\r\n"
					+ "  height: 50px;\r\n"
					+ "  min-width: 190px;\r\n"
					+ "  padding: 0 15px 0 2px;\r\n"
					+ "}\r\n"
					+ "nav .profile-details img{\r\n"
					+ "  height: 40px;\r\n"
					+ "  width: 40px;\r\n"
					+ "  border-radius: 6px;\r\n"
					+ "  object-fit: cover;\r\n"
					+ "}\r\n"
					+ "nav .profile-details .admin_name{\r\n"
					+ "  font-size: 15px;\r\n"
					+ "  font-weight: 500;\r\n"
					+ "  color: #333;\r\n"
					+ "  margin: 0 10px;\r\n"
					+ "  white-space: nowrap;\r\n"
					+ "}\r\n"
					+ "nav .profile-details i{\r\n"
					+ "  font-size: 25px;\r\n"
					+ "  color: #333;\r\n"
					+ "}\r\n"
					+ ".home-section .home-content{\r\n"
					+ "  position: relative;\r\n"
					+ "  padding-top: 104px;\r\n"
					+ "}\r\n"
					+ ".home-content .overview-boxes{\r\n"
					+ "  display: flex;\r\n"
					+ "  align-items: center;\r\n"
					+ "  justify-content: space-between;\r\n"
					+ "  flex-wrap: wrap;\r\n"
					+ "  padding: 0 20px;\r\n"
					+ "  margin-bottom: 26px;\r\n"
					+ "}\r\n"
					+ ".overview-boxes .box{\r\n"
					+ "  display: flex;\r\n"
					+ "  align-items: center;\r\n"
					+ "  justify-content: center;\r\n"
					+ "  width: calc(100% / 4 - 15px);\r\n"
					+ "  background: #fff;\r\n"
					+ "  padding: 15px 14px;\r\n"
					+ "  border-radius: 12px;\r\n"
					+ "  box-shadow: 0 5px 10px rgba(0,0,0,0.1);\r\n"
					+ "}\r\n"
					+ ".overview-boxes .box-topic{\r\n"
					+ "  font-size: 20px;\r\n"
					+ "  font-weight: 500;\r\n"
					+ "}\r\n"
					+ ".home-content .box .number{\r\n"
					+ "  display: inline-block;\r\n"
					+ "  font-size: 35px;\r\n"
					+ "  margin-top: -6px;\r\n"
					+ "  font-weight: 500;\r\n"
					+ "}\r\n"
					+ ".home-content .box .indicator{\r\n"
					+ "  display: flex;\r\n"
					+ "  align-items: center;\r\n"
					+ "}\r\n"
					+ ".home-content .box .indicator i{\r\n"
					+ "  height: 20px;\r\n"
					+ "  width: 20px;\r\n"
					+ "  background: #8FDACB;\r\n"
					+ "  line-height: 20px;\r\n"
					+ "  text-align: center;\r\n"
					+ "  border-radius: 50%;\r\n"
					+ "  color: #fff;\r\n"
					+ "  font-size: 20px;\r\n"
					+ "  margin-right: 5px;\r\n"
					+ "}\r\n"
					+ ".box .indicator i.down{\r\n"
					+ "  background: #e87d88;\r\n"
					+ "}\r\n"
					+ ".home-content .box .indicator .text{\r\n"
					+ "  font-size: 12px;\r\n"
					+ "}\r\n"
					+ ".home-content .box .cart{\r\n"
					+ "  display: inline-block;\r\n"
					+ "  font-size: 32px;\r\n"
					+ "  height: 50px;\r\n"
					+ "  width: 50px;\r\n"
					+ "  background: #cce5ff;\r\n"
					+ "  line-height: 50px;\r\n"
					+ "  text-align: center;\r\n"
					+ "  color: #66b0ff;\r\n"
					+ "  border-radius: 12px;\r\n"
					+ "  margin: -15px 0 0 6px;\r\n"
					+ "}\r\n"
					+ ".home-content .box .cart.two{\r\n"
					+ "   color: #2BD47D;\r\n"
					+ "   background: #C0F2D8;\r\n"
					+ " }\r\n"
					+ ".home-content .box .cart.three{\r\n"
					+ "   color: #ffc233;\r\n"
					+ "   background: #ffe8b3;\r\n"
					+ " }\r\n"
					+ ".home-content .box .cart.four{\r\n"
					+ "   color: #e05260;\r\n"
					+ "   background: #f7d4d7;\r\n"
					+ " }\r\n"
					+ ".home-content .total-order{\r\n"
					+ "  font-size: 20px;\r\n"
					+ "  font-weight: 500;\r\n"
					+ "}\r\n"
					+ ".home-content .sales-boxes{\r\n"
					+ "  display: flex;\r\n"
					+ "  justify-content: space-between;\r\n"
					+ "  /* padding: 0 20px; */\r\n"
					+ "}\r\n"
					+ "\r\n"
					+ "/* left box */\r\n"
					+ ".home-content .sales-boxes .recent-sales{\r\n"
					+ "  width: 65%;\r\n"
					+ "  background: #fff;\r\n"
					+ "  padding: 20px 30px;\r\n"
					+ "  margin: 0 20px;\r\n"
					+ "  border-radius: 12px;\r\n"
					+ "  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);\r\n"
					+ "}\r\n"
					+ ".home-content .sales-boxes .sales-details{\r\n"
					+ "  display: flex;\r\n"
					+ "  align-items: center;\r\n"
					+ "  justify-content: space-between;\r\n"
					+ "}\r\n"
					+ ".sales-boxes .box .title{\r\n"
					+ "  font-size: 24px;\r\n"
					+ "  font-weight: 500;\r\n"
					+ "  /* margin-bottom: 10px; */\r\n"
					+ "}\r\n"
					+ ".sales-boxes .sales-details li.topic{\r\n"
					+ "  font-size: 20px;\r\n"
					+ "  font-weight: 500;\r\n"
					+ "}\r\n"
					+ ".sales-boxes .sales-details li{\r\n"
					+ "  list-style: none;\r\n"
					+ "  margin: 8px 0;\r\n"
					+ "}\r\n"
					+ ".sales-boxes .sales-details li a{\r\n"
					+ "  font-size: 18px;\r\n"
					+ "  color: #333;\r\n"
					+ "  font-size: 400;\r\n"
					+ "  text-decoration: none;\r\n"
					+ "}\r\n"
					+ ".sales-boxes .box .button{\r\n"
					+ "  width: 100%;\r\n"
					+ "  display: flex;\r\n"
					+ "  justify-content: flex-end;\r\n"
					+ "}\r\n"
					+ ".sales-boxes .box .button a{\r\n"
					+ "  color: #fff;\r\n"
					+ "  background: #0A2558;\r\n"
					+ "  padding: 4px 12px;\r\n"
					+ "  font-size: 15px;\r\n"
					+ "  font-weight: 400;\r\n"
					+ "  border-radius: 4px;\r\n"
					+ "  text-decoration: none;\r\n"
					+ "  transition: all 0.3s ease;\r\n"
					+ "}\r\n"
					+ ".sales-boxes .box .button a:hover{\r\n"
					+ "  background:  #0d3073;\r\n"
					+ "}\r\n"
					+ "\r\n"
					+ "/* Right box */\r\n"
					+ ".home-content .sales-boxes .top-sales{\r\n"
					+ "  width: 35%;\r\n"
					+ "  background: #fff;\r\n"
					+ "  padding: 20px 30px;\r\n"
					+ "  margin: 0 20px 0 0;\r\n"
					+ "  border-radius: 12px;\r\n"
					+ "  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);\r\n"
					+ "}\r\n"
					+ ".sales-boxes .top-sales li{\r\n"
					+ "  display: flex;\r\n"
					+ "  align-items: center;\r\n"
					+ "  justify-content: space-between;\r\n"
					+ "  margin: 10px 0;\r\n"
					+ "}\r\n"
					+ ".sales-boxes .top-sales li a img{\r\n"
					+ "  height: 40px;\r\n"
					+ "  width: 40px;\r\n"
					+ "  object-fit: cover;\r\n"
					+ "  border-radius: 12px;\r\n"
					+ "  margin-right: 10px;\r\n"
					+ "  background: #333;\r\n"
					+ "}\r\n"
					+ ".sales-boxes .top-sales li a{\r\n"
					+ "  display: flex;\r\n"
					+ "  align-items: center;\r\n"
					+ "  text-decoration: none;\r\n"
					+ "}\r\n"
					+ ".sales-boxes .top-sales li .product,\r\n"
					+ ".price{\r\n"
					+ "  font-size: 17px;\r\n"
					+ "  font-weight: 400;\r\n"
					+ "  color: #333;\r\n"
					+ "}\r\n"
					+ "/* Responsive Media Query */\r\n"
					+ "@media (max-width: 1240px) {\r\n"
					+ "  .sidebar{\r\n"
					+ "    width: 60px;\r\n"
					+ "  }\r\n"
					+ "  .sidebar.active{\r\n"
					+ "    width: 220px;\r\n"
					+ "  }\r\n"
					+ "  .home-section{\r\n"
					+ "    width: calc(100% - 60px);\r\n"
					+ "    left: 60px;\r\n"
					+ "  }\r\n"
					+ "  .sidebar.active ~ .home-section{\r\n"
					+ "    /* width: calc(100% - 220px); */\r\n"
					+ "    overflow: hidden;\r\n"
					+ "    left: 220px;\r\n"
					+ "  }\r\n"
					+ "  .home-section nav{\r\n"
					+ "    width: calc(100% - 60px);\r\n"
					+ "    left: 60px;\r\n"
					+ "  }\r\n"
					+ "  .sidebar.active ~ .home-section nav{\r\n"
					+ "    width: calc(100% - 220px);\r\n"
					+ "    left: 220px;\r\n"
					+ "  }\r\n"
					+ "}\r\n"
					+ "@media (max-width: 1150px) {\r\n"
					+ "  .home-content .sales-boxes{\r\n"
					+ "    flex-direction: column;\r\n"
					+ "  }\r\n"
					+ "  .home-content .sales-boxes .box{\r\n"
					+ "    width: 100%;\r\n"
					+ "    overflow-x: scroll;\r\n"
					+ "    margin-bottom: 30px;\r\n"
					+ "  }\r\n"
					+ "  .home-content .sales-boxes .top-sales{\r\n"
					+ "    margin: 0;\r\n"
					+ "  }\r\n"
					+ "}\r\n"
					+ "@media (max-width: 1000px) {\r\n"
					+ "  .overview-boxes .box{\r\n"
					+ "    width: calc(100% / 2 - 15px);\r\n"
					+ "    margin-bottom: 15px;\r\n"
					+ "  }\r\n"
					+ "}\r\n"
					+ "@media (max-width: 700px) {\r\n"
					+ "  nav .sidebar-button .dashboard,\r\n"
					+ "  nav .profile-details .admin_name,\r\n"
					+ "  nav .profile-details i{\r\n"
					+ "    display: none;\r\n"
					+ "  }\r\n"
					+ "  .home-section nav .profile-details{\r\n"
					+ "    height: 50px;\r\n"
					+ "    min-width: 40px;\r\n"
					+ "  }\r\n"
					+ "  .home-content .sales-boxes .sales-details{\r\n"
					+ "    width: 560px;\r\n"
					+ "  }\r\n"
					+ "}\r\n"
					+ "@media (max-width: 550px) {\r\n"
					+ "  .overview-boxes .box{\r\n"
					+ "    width: 100%;\r\n"
					+ "    margin-bottom: 15px;\r\n"
					+ "  }\r\n"
					+ "  .sidebar.active ~ .home-section nav .profile-details{\r\n"
					+ "    display: none;\r\n"
					+ "  }\r\n"
					+ "}\r\n"
					+ "  \r\n"
					+ "  </style>\r\n"
					+ "    <meta charset=\"UTF-8\">\r\n"
					+ "    <!--<title> Responsiive Admin Dashboard | CodingLab </title>-->\r\n"
					+ "    <link rel=\"stylesheet\" href=\"style.css\">\r\n"
					+ "    <!-- Boxicons CDN Link -->\r\n"
					+ "    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>\r\n"
					+ "     <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
					+ "   </head>\r\n"
					+ "<body>\r\n"
					+ "  <div class=\"sidebar\">\r\n"
					+ "    <div class=\"logo-details\">\r\n"
					+ "<i class='bx bx-male'></i>\r\n"
					+ "      <span class=\"logo_name\">Customer</span>\r\n"
					+ "    </div>\r\n"
					+ "    <hr>\r\n"
					+ "      <ul class=\"nav-links\">\r\n"
					+ "        \r\n"
					+ "        <li>\r\n"
					+ "          <a href=\"View.jsp\">\r\n"
					+ "           <i class='bx bx-user-plus'></i>\r\n"
					+ "            <span class=\"links_name\">View Specialist </span>\r\n"
					+ "          </a>\r\n"
					+ "        </li>\r\n"
					+ "        <li>\r\n"
					+ "          <a href=\"BillNew.jsp\">\r\n"
					+ "           <i class='bx bx-capsule'></i>\r\n"
					+ "            <span class=\"links_name\">View Medicine </span>\r\n"
					+ "          </a>\r\n"
					+ "        </li>\r\n"
					+ "        <li>\r\n"
					+ "          <a href=\"Bill\">\r\n"
					+ "           <i class='bx bx-money'></i>\r\n"
					+ "            <span class=\"links_name\">Bills and Purchases </span>\r\n"
					+ "          </a>\r\n"
					+ "        </li>\r\n"
					+ "       \r\n"
					+ "        \r\n"
					+ "        <li class=\"log_out\">\r\n"
					+ "          <a href=\"index.jsp\">\r\n"
					+ "            <i class='bx bx-log-out'></i>\r\n"
					+ "            <span class=\"links_name\">Log out</span>\r\n"
					+ "          </a>\r\n"
					+ "        </li>\r\n"
					+ "         <li>\r\n"
					+ "          <a href=\"help.jsp\">\r\n"
					+ "            <i class='bx bx-help-circle' ></i>\r\n"
					+ "            <span class=\"links_name\">Help</span>\r\n"
					+ "          </a>\r\n"
					+ "        </li>\r\n"
					+ "      </ul>\r\n"
					+ "  </div>\r\n"
					+ "\r\n"
					+ "  <section class=\"home-section\">\r\n"
					+ "    <nav>\r\n"
					+ "      <div class=\"sidebar-button\">\r\n"
					+ "        <i class='bx bx-menu sidebarBtn'></i>\r\n"
					+ "        <span class=\"dashboard\">Dashboard</span>\r\n"
					+ "      </div>\r\n"
					+ "      <div class=\"search-box\">\r\n"
					+ "        <input type=\"text\" placeholder=\"Enter Doctor's Name\">\r\n"
					+ "        <i class='bx bx-search' ></i>\r\n"
					+ "      </div>\r\n"
					+ "    </nav>\r\n"
					+ "    <div class=\"home-content\">\r\n"
					+ "  	<div class=\"invoice-box\">\r\n"
					+ "			<table cellpadding=\"0\" cellspacing=\"0\">\r\n"
					+ "				<tr class=\"top\">\r\n"
					+ "					<td colspan=\"2\">\r\n"
					+ "						<table>\r\n"
					+ "							<tr>\r\n"
					+ "								<td class=\"title\">\r\n"
					+ "									<img src=\"https://www.sparksuite.com/images/logo.png\" style=\"width: 100%; max-width: 300px\" />\r\n"
					+ "								</td>\r\n"
					+ "\r\n"
					+ "								\r\n"
					+ "							</tr>\r\n"
					+ "						</table>\r\n"
					+ "					</td>\r\n"
					+ "				</tr>\r\n"
					+ "\r\n"
					+ "				<tr class=\"information\">\r\n"
					+ "					<td colspan=\"2\">\r\n"
					+ "						<table>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									Fortis Hospital<br />\r\n"
					+ "									122001 Gurgaon<br />\r\n"
					+ "									Haryana\r\n"
					+ "								</td>\r\n"
					+ "\r\n"
					+ "								\r\n"
					+ "							</tr>\r\n"
					+ "						</table>\r\n"
					+ "					</td>\r\n"
					+ "				</tr>\r\n"
					+ "\r\n"
					+ "				<tr class=\"heading\">\r\n"
					+ "					<td>Payment Method</td>\r\n"
					+ "\r\n"
					+ "					<td>Method </td>\r\n"
					+ "				</tr>\r\n"
					+ "\r\n"
					+ "				<tr class=\"details\">\r\n"
					+ "					<td>Cash on Delivery</td>\r\n"
					+ "\r\n"
					+ "					<td>COD</td>\r\n"
					+ "				</tr>\r\n"
					+ "\r\n"
					+ "				<tr class=\"heading\">\r\n"
					+ "					<td>Doctor's</td>\r\n"
					+ "\r\n"
					+ "					<td>Timings</td>\r\n"
					+ "				</tr>");
			while(rs.next())
			{
				
				sqid = rs.getString("name");
				sqname = rs.getString("timings");
				
				out.println("<tr><td>" + sqid + "</td><td>" + sqname + "</td></tr>");
				System.out.println(sqid);
				System.out.println(sqname);
			}
			
			}
		catch(ClassNotFoundException e)
		{
			e.printStackTrace();
		}
		catch(SQLException e)
		{
			e.printStackTrace();
		}
		out.println(""
				+ "			</table>\r\n"
				+ "		</div>\r\n"
				+ "\r\n"
				+ "  <script>\r\n"
				+ "   let sidebar = document.querySelector(\".sidebar\");\r\n"
				+ "let sidebarBtn = document.querySelector(\".sidebarBtn\");\r\n"
				+ "sidebarBtn.onclick = function() {\r\n"
				+ "  sidebar.classList.toggle(\"active\");\r\n"
				+ "  if(sidebar.classList.contains(\"active\")){\r\n"
				+ "  sidebarBtn.classList.replace(\"bx-menu\" ,\"bx-menu-alt-right\");\r\n"
				+ "}else\r\n"
				+ "  sidebarBtn.classList.replace(\"bx-menu-alt-right\", \"bx-menu\");\r\n"
				+ "}\r\n"
				+ " </script>\r\n"
				+ "\r\n"
				+ "</body>\r\n"
				+ "</html>");
		session.setAttribute("attributeName",sqid);
		session.setAttribute("attributeName1",sqname);
	}

	

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
		
}
}
