package logistics;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.servlet.ServletException;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class ViewCartItems
 */
public class ViewCartItems extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public ViewCartItems() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
//		
	
		
	        }
	

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		response.setContentType("text/html");
		PrintWriter pw = response.getWriter();
		try {
	        Class.forName("com.mysql.cj.jdbc.Driver");
	        String url1 = "jdbc:mysql://localhost:3306/healthcareproject";
	        String username1 = "root";
	        String pass1 = "20csu214";
	       Connection con = DriverManager.getConnection(url1, username1, pass1);
	       ResultSet rs;
	       String q;
	       PreparedStatement pst;
	       Cookie c =new Cookie(request.getParameter("ItemId"),"1");
	       c.setMaxAge(0);
	       response.addCookie(c);
	       pw.print("product removed");
	       pw.print("<a href = 'BillCart'>Back</a>");
	       Cookie ck[] = request.getCookies();
	       pw.print("\"<!DOCTYPE html>\\r\\n\"\r\n"
	       		+ "    			+ \"<!-- Designined by CodingLab | www.youtube.com/codinglabyt -->\\r\\n\"\r\n"
	       		+ "    			+ \"<html lang=\\\"en\\\" dir=\\\"ltr\\\">\\r\\n\"\r\n"
	       		+ "    			+ \"  <head>\\r\\n\"\r\n"
	       		+ "    			+ \" <script\\r\\n\"\r\n"
	       		+ "    			+ \"      src=\\\"https://kit.fontawesome.com/64d58efce2.js\\\"\\r\\n\"\r\n"
	       		+ "    			+ \"      crossorigin=\\\"anonymous\\\"\\r\\n\"\r\n"
	       		+ "    			+ \"    ></script>\\r\\n\"\r\n"
	       		+ "    			+ \"   <style>\\r\\n\"\r\n"
	       		+ "    			+ \"    .invoice-box {\\r\\n\"\r\n"
	       		+ "    			+ \"				max-width: 800px;\\r\\n\"\r\n"
	       		+ "    			+ \"				margin: auto;\\r\\n\"\r\n"
	       		+ "    			+ \"				padding: 30px;\\r\\n\"\r\n"
	       		+ "    			+ \"				border: 1px solid #eee;\\r\\n\"\r\n"
	       		+ "    			+ \"				box-shadow: 0 0 10px rgba(0, 0, 0, 0.15);\\r\\n\"\r\n"
	       		+ "    			+ \"				font-size: 16px;\\r\\n\"\r\n"
	       		+ "    			+ \"				line-height: 24px;\\r\\n\"\r\n"
	       		+ "    			+ \"				font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;\\r\\n\"\r\n"
	       		+ "    			+ \"				color: #555;\\r\\n\"\r\n"
	       		+ "    			+ \"			}\\r\\n\"\r\n"
	       		+ "    			+ \"\\r\\n\"\r\n"
	       		+ "    			+ \"			.invoice-box table {\\r\\n\"\r\n"
	       		+ "    			+ \"				width: 100%;\\r\\n\"\r\n"
	       		+ "    			+ \"				line-height: inherit;\\r\\n\"\r\n"
	       		+ "    			+ \"				text-align: left;\\r\\n\"\r\n"
	       		+ "    			+ \"			}\\r\\n\"\r\n"
	       		+ "    			+ \"\\r\\n\"\r\n"
	       		+ "    			+ \"			.invoice-box table td {\\r\\n\"\r\n"
	       		+ "    			+ \"				padding: 16px;\\r\\n\"\r\n"
	       		+ "    			+ \"				vertical-align: top;\\r\\n\"\r\n"
	       		+ "    			+ \"			}\\r\\n\"\r\n"
	       		+ "    			+ \"\\r\\n\"\r\n"
	       		+ "    			+ \"			.invoice-box table tr td:nth-child(2) {\\r\\n\"\r\n"
	       		+ "    			+ \"				text-align: left;\\r\\n\"\r\n"
	       		+ "    			+ \"			}\\r\\n\"\r\n"
	       		+ "    			+ \"\\r\\n\"\r\n"
	       		+ "    			+ \"			.invoice-box table tr.top table td {\\r\\n\"\r\n"
	       		+ "    			+ \"				padding-bottom: 20px;\\r\\n\"\r\n"
	       		+ "    			+ \"			}\\r\\n\"\r\n"
	       		+ "    			+ \"\\r\\n\"\r\n"
	       		+ "    			+ \"			.invoice-box table tr.top table td.title {\\r\\n\"\r\n"
	       		+ "    			+ \"				font-size: 45px;\\r\\n\"\r\n"
	       		+ "    			+ \"				line-height: 45px;\\r\\n\"\r\n"
	       		+ "    			+ \"				color: #333;\\r\\n\"\r\n"
	       		+ "    			+ \"			}\\r\\n\"\r\n"
	       		+ "    			+ \"\\r\\n\"\r\n"
	       		+ "    			+ \"			.invoice-box table tr.information table td {\\r\\n\"\r\n"
	       		+ "    			+ \"				padding-bottom: 40px;\\r\\n\"\r\n"
	       		+ "    			+ \"			}\\r\\n\"\r\n"
	       		+ "    			+ \"\\r\\n\"\r\n"
	       		+ "    			+ \"			.invoice-box table tr.heading td {\\r\\n\"\r\n"
	       		+ "    			+ \"				background: #eee;\\r\\n\"\r\n"
	       		+ "    			+ \"				border-bottom: 1px solid #ddd;\\r\\n\"\r\n"
	       		+ "    			+ \"				font-weight: bold;\\r\\n\"\r\n"
	       		+ "    			+ \"			}\\r\\n\"\r\n"
	       		+ "    			+ \"\\r\\n\"\r\n"
	       		+ "    			+ \"			.invoice-box table tr.details td {\\r\\n\"\r\n"
	       		+ "    			+ \"				padding-bottom: 20px;\\r\\n\"\r\n"
	       		+ "    			+ \"			}\\r\\n\"\r\n"
	       		+ "    			+ \"\\r\\n\"\r\n"
	       		+ "    			+ \"			.invoice-box table tr.item td {\\r\\n\"\r\n"
	       		+ "    			+ \"				border-bottom: 1px solid #eee;\\r\\n\"\r\n"
	       		+ "    			+ \"			}\\r\\n\"\r\n"
	       		+ "    			+ \"\\r\\n\"\r\n"
	       		+ "    			+ \"			.invoice-box table tr.item.last td {\\r\\n\"\r\n"
	       		+ "    			+ \"				border-bottom: none;\\r\\n\"\r\n"
	       		+ "    			+ \"			}\\r\\n\"\r\n"
	       		+ "    			+ \"\\r\\n\"\r\n"
	       		+ "    			+ \"			.invoice-box table tr.total td:nth-child(2) {\\r\\n\"\r\n"
	       		+ "    			+ \"				border-top: 2px solid #eee;\\r\\n\"\r\n"
	       		+ "    			+ \"				font-weight: bold;\\r\\n\"\r\n"
	       		+ "    			+ \"			}\\r\\n\"\r\n"
	       		+ "    			+ \"\\r\\n\"\r\n"
	       		+ "    			+ \"			@media only screen and (max-width: 600px) {\\r\\n\"\r\n"
	       		+ "    			+ \"				.invoice-box table tr.top table td {\\r\\n\"\r\n"
	       		+ "    			+ \"					width: 100%;\\r\\n\"\r\n"
	       		+ "    			+ \"					display: block;\\r\\n\"\r\n"
	       		+ "    			+ \"					text-align: center;\\r\\n\"\r\n"
	       		+ "    			+ \"				}\\r\\n\"\r\n"
	       		+ "    			+ \"\\r\\n\"\r\n"
	       		+ "    			+ \"				.invoice-box table tr.information table td {\\r\\n\"\r\n"
	       		+ "    			+ \"					width: 100%;\\r\\n\"\r\n"
	       		+ "    			+ \"					display: block;\\r\\n\"\r\n"
	       		+ "    			+ \"					text-align: center;\\r\\n\"\r\n"
	       		+ "    			+ \"				}\\r\\n\"\r\n"
	       		+ "    			+ \"			}\\r\\n\"\r\n"
	       		+ "    			+ \"\\r\\n\"\r\n"
	       		+ "    			+ \"			/** RTL **/\\r\\n\"\r\n"
	       		+ "    			+ \"			.invoice-box.rtl {\\r\\n\"\r\n"
	       		+ "    			+ \"				direction: rtl;\\r\\n\"\r\n"
	       		+ "    			+ \"				font-family: Tahoma, 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;\\r\\n\"\r\n"
	       		+ "    			+ \"			}\\r\\n\"\r\n"
	       		+ "    			+ \"\\r\\n\"\r\n"
	       		+ "    			+ \"			.invoice-box.rtl table {\\r\\n\"\r\n"
	       		+ "    			+ \"				text-align: right;\\r\\n\"\r\n"
	       		+ "    			+ \"			}\\r\\n\"\r\n"
	       		+ "    			+ \"\\r\\n\"\r\n"
	       		+ "    			+ \"			.invoice-box.rtl table tr td:nth-child(2) {\\r\\n\"\r\n"
	       		+ "    			+ \"				text-align: left;\\r\\n\"\r\n"
	       		+ "    			+ \"			}\\r\\n\"\r\n"
	       		+ "    			+ \"  /* Googlefont Poppins CDN Link */\\r\\n\"\r\n"
	       		+ "    			+ \"@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');\\r\\n\"\r\n"
	       		+ "    			+ \"*{\\r\\n\"\r\n"
	       		+ "    			+ \"  margin: 0;\\r\\n\"\r\n"
	       		+ "    			+ \"  padding: 0;\\r\\n\"\r\n"
	       		+ "    			+ \"  box-sizing: border-box;\\r\\n\"\r\n"
	       		+ "    			+ \"  font-family: 'Poppins', sans-serif;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".sidebar{\\r\\n\"\r\n"
	       		+ "    			+ \"  position: fixed;\\r\\n\"\r\n"
	       		+ "    			+ \"  height: 100%;\\r\\n\"\r\n"
	       		+ "    			+ \"  width: 240px;\\r\\n\"\r\n"
	       		+ "    			+ \"  background: #289d75;\\r\\n\"\r\n"
	       		+ "    			+ \"  transition: all 0.5s ease;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".sidebar.active{\\r\\n\"\r\n"
	       		+ "    			+ \"  width: 60px;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".sidebar .logo-details{\\r\\n\"\r\n"
	       		+ "    			+ \"  height: 80px;\\r\\n\"\r\n"
	       		+ "    			+ \"  display: flex;\\r\\n\"\r\n"
	       		+ "    			+ \"  align-items: center;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".sidebar .logo-details i{\\r\\n\"\r\n"
	       		+ "    			+ \"  font-size: 28px;\\r\\n\"\r\n"
	       		+ "    			+ \"  font-weight: 500;\\r\\n\"\r\n"
	       		+ "    			+ \"  color: #fff;\\r\\n\"\r\n"
	       		+ "    			+ \"  min-width: 60px;\\r\\n\"\r\n"
	       		+ "    			+ \"  text-align: center\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".sidebar .logo-details .logo_name{\\r\\n\"\r\n"
	       		+ "    			+ \"  color: #fff;\\r\\n\"\r\n"
	       		+ "    			+ \"  font-size: 24px;\\r\\n\"\r\n"
	       		+ "    			+ \"  font-weight: 500;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".sidebar .nav-links{\\r\\n\"\r\n"
	       		+ "    			+ \"  margin-top: 10px;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".sidebar .nav-links li{\\r\\n\"\r\n"
	       		+ "    			+ \"  position: relative;\\r\\n\"\r\n"
	       		+ "    			+ \"  list-style: none;\\r\\n\"\r\n"
	       		+ "    			+ \"  height: 50px;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".sidebar .nav-links li a{\\r\\n\"\r\n"
	       		+ "    			+ \"  height: 100%;\\r\\n\"\r\n"
	       		+ "    			+ \"  width: 100%;\\r\\n\"\r\n"
	       		+ "    			+ \"  display: flex;\\r\\n\"\r\n"
	       		+ "    			+ \"  align-items: center;\\r\\n\"\r\n"
	       		+ "    			+ \"  text-decoration: none;\\r\\n\"\r\n"
	       		+ "    			+ \"  transition: all 0.4s ease;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".sidebar .nav-links li a.active{\\r\\n\"\r\n"
	       		+ "    			+ \"  background:#08563c;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".sidebar .nav-links li a:hover{\\r\\n\"\r\n"
	       		+ "    			+ \"  background: #08563c;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".sidebar .nav-links li i{\\r\\n\"\r\n"
	       		+ "    			+ \"  min-width: 60px;\\r\\n\"\r\n"
	       		+ "    			+ \"  text-align: center;\\r\\n\"\r\n"
	       		+ "    			+ \"  font-size: 18px;\\r\\n\"\r\n"
	       		+ "    			+ \"  color: #fff;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".sidebar .nav-links li a .links_name{\\r\\n\"\r\n"
	       		+ "    			+ \"  color: #fff;\\r\\n\"\r\n"
	       		+ "    			+ \"  font-size: 15px;\\r\\n\"\r\n"
	       		+ "    			+ \"  font-weight: 400;\\r\\n\"\r\n"
	       		+ "    			+ \"  white-space: nowrap;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".sidebar .nav-links .log_out{\\r\\n\"\r\n"
	       		+ "    			+ \"  position: absolute;\\r\\n\"\r\n"
	       		+ "    			+ \"  bottom: 0;\\r\\n\"\r\n"
	       		+ "    			+ \"  width: 100%;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".home-section{\\r\\n\"\r\n"
	       		+ "    			+ \"  position: relative;\\r\\n\"\r\n"
	       		+ "    			+ \"  background: #f5f5f5;\\r\\n\"\r\n"
	       		+ "    			+ \"  min-height: 100vh;\\r\\n\"\r\n"
	       		+ "    			+ \"  width: calc(100% - 240px);\\r\\n\"\r\n"
	       		+ "    			+ \"  left: 240px;\\r\\n\"\r\n"
	       		+ "    			+ \"  transition: all 0.5s ease;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".sidebar.active ~ .home-section{\\r\\n\"\r\n"
	       		+ "    			+ \"  width: calc(100% - 60px);\\r\\n\"\r\n"
	       		+ "    			+ \"  left: 60px;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".home-section nav{\\r\\n\"\r\n"
	       		+ "    			+ \"  display: flex;\\r\\n\"\r\n"
	       		+ "    			+ \"  justify-content: space-between;\\r\\n\"\r\n"
	       		+ "    			+ \"  height: 80px;\\r\\n\"\r\n"
	       		+ "    			+ \"  background: #fff;\\r\\n\"\r\n"
	       		+ "    			+ \"  display: flex;\\r\\n\"\r\n"
	       		+ "    			+ \"  align-items: center;\\r\\n\"\r\n"
	       		+ "    			+ \"  position: fixed;\\r\\n\"\r\n"
	       		+ "    			+ \"  width: calc(100% - 240px);\\r\\n\"\r\n"
	       		+ "    			+ \"  left: 240px;\\r\\n\"\r\n"
	       		+ "    			+ \"  z-index: 100;\\r\\n\"\r\n"
	       		+ "    			+ \"  padding: 0 20px;\\r\\n\"\r\n"
	       		+ "    			+ \"  box-shadow: 0 1px 1px rgba(0, 0, 0, 0.1);\\r\\n\"\r\n"
	       		+ "    			+ \"  transition: all 0.5s ease;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".sidebar.active ~ .home-section nav{\\r\\n\"\r\n"
	       		+ "    			+ \"  left: 60px;\\r\\n\"\r\n"
	       		+ "    			+ \"  width: calc(100% - 60px);\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".home-section nav .sidebar-button{\\r\\n\"\r\n"
	       		+ "    			+ \"  display: flex;\\r\\n\"\r\n"
	       		+ "    			+ \"  align-items: center;\\r\\n\"\r\n"
	       		+ "    			+ \"  font-size: 24px;\\r\\n\"\r\n"
	       		+ "    			+ \"  font-weight: 500;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \"nav .sidebar-button i{\\r\\n\"\r\n"
	       		+ "    			+ \"  font-size: 35px;\\r\\n\"\r\n"
	       		+ "    			+ \"  margin-right: 10px;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".home-section nav .search-box{\\r\\n\"\r\n"
	       		+ "    			+ \"  position: relative;\\r\\n\"\r\n"
	       		+ "    			+ \"  height: 50px;\\r\\n\"\r\n"
	       		+ "    			+ \"  max-width: 550px;\\r\\n\"\r\n"
	       		+ "    			+ \"  width: 100%;\\r\\n\"\r\n"
	       		+ "    			+ \"  margin: 0 20px;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \"nav .search-box input{\\r\\n\"\r\n"
	       		+ "    			+ \"  height: 100%;\\r\\n\"\r\n"
	       		+ "    			+ \"  width: 100%;\\r\\n\"\r\n"
	       		+ "    			+ \"  outline: none;\\r\\n\"\r\n"
	       		+ "    			+ \"  background: #F5F6FA;\\r\\n\"\r\n"
	       		+ "    			+ \"  border: 2px solid #EFEEF1;\\r\\n\"\r\n"
	       		+ "    			+ \"  border-radius: 6px;\\r\\n\"\r\n"
	       		+ "    			+ \"  font-size: 18px;\\r\\n\"\r\n"
	       		+ "    			+ \"  padding: 0 15px;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \"nav .search-box .bx-search{\\r\\n\"\r\n"
	       		+ "    			+ \"  position: absolute;\\r\\n\"\r\n"
	       		+ "    			+ \"  height: 40px;\\r\\n\"\r\n"
	       		+ "    			+ \"  width: 40px;\\r\\n\"\r\n"
	       		+ "    			+ \"  background: #2697FF;\\r\\n\"\r\n"
	       		+ "    			+ \"  right: 5px;\\r\\n\"\r\n"
	       		+ "    			+ \"  top: 50%;\\r\\n\"\r\n"
	       		+ "    			+ \"  transform: translateY(-50%);\\r\\n\"\r\n"
	       		+ "    			+ \"  border-radius: 4px;\\r\\n\"\r\n"
	       		+ "    			+ \"  line-height: 40px;\\r\\n\"\r\n"
	       		+ "    			+ \"  text-align: center;\\r\\n\"\r\n"
	       		+ "    			+ \"  color: #fff;\\r\\n\"\r\n"
	       		+ "    			+ \"  font-size: 22px;\\r\\n\"\r\n"
	       		+ "    			+ \"  transition: all 0.4 ease;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".home-section nav .profile-details{\\r\\n\"\r\n"
	       		+ "    			+ \"  display: flex;\\r\\n\"\r\n"
	       		+ "    			+ \"  align-items: center;\\r\\n\"\r\n"
	       		+ "    			+ \"  background: #F5F6FA;\\r\\n\"\r\n"
	       		+ "    			+ \"  border: 2px solid #EFEEF1;\\r\\n\"\r\n"
	       		+ "    			+ \"  border-radius: 6px;\\r\\n\"\r\n"
	       		+ "    			+ \"  height: 50px;\\r\\n\"\r\n"
	       		+ "    			+ \"  min-width: 190px;\\r\\n\"\r\n"
	       		+ "    			+ \"  padding: 0 15px 0 2px;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \"nav .profile-details img{\\r\\n\"\r\n"
	       		+ "    			+ \"  height: 40px;\\r\\n\"\r\n"
	       		+ "    			+ \"  width: 40px;\\r\\n\"\r\n"
	       		+ "    			+ \"  border-radius: 6px;\\r\\n\"\r\n"
	       		+ "    			+ \"  object-fit: cover;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \"nav .profile-details .admin_name{\\r\\n\"\r\n"
	       		+ "    			+ \"  font-size: 15px;\\r\\n\"\r\n"
	       		+ "    			+ \"  font-weight: 500;\\r\\n\"\r\n"
	       		+ "    			+ \"  color: #333;\\r\\n\"\r\n"
	       		+ "    			+ \"  margin: 0 10px;\\r\\n\"\r\n"
	       		+ "    			+ \"  white-space: nowrap;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \"nav .profile-details i{\\r\\n\"\r\n"
	       		+ "    			+ \"  font-size: 25px;\\r\\n\"\r\n"
	       		+ "    			+ \"  color: #333;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".home-section .home-content{\\r\\n\"\r\n"
	       		+ "    			+ \"  position: relative;\\r\\n\"\r\n"
	       		+ "    			+ \"  padding-top: 104px;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".home-content .overview-boxes{\\r\\n\"\r\n"
	       		+ "    			+ \"  display: flex;\\r\\n\"\r\n"
	       		+ "    			+ \"  align-items: center;\\r\\n\"\r\n"
	       		+ "    			+ \"  justify-content: space-between;\\r\\n\"\r\n"
	       		+ "    			+ \"  flex-wrap: wrap;\\r\\n\"\r\n"
	       		+ "    			+ \"  padding: 0 20px;\\r\\n\"\r\n"
	       		+ "    			+ \"  margin-bottom: 26px;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".overview-boxes .box{\\r\\n\"\r\n"
	       		+ "    			+ \"  display: flex;\\r\\n\"\r\n"
	       		+ "    			+ \"  align-items: center;\\r\\n\"\r\n"
	       		+ "    			+ \"  justify-content: center;\\r\\n\"\r\n"
	       		+ "    			+ \"  width: calc(100% / 4 - 15px);\\r\\n\"\r\n"
	       		+ "    			+ \"  background: #fff;\\r\\n\"\r\n"
	       		+ "    			+ \"  padding: 15px 14px;\\r\\n\"\r\n"
	       		+ "    			+ \"  border-radius: 12px;\\r\\n\"\r\n"
	       		+ "    			+ \"  box-shadow: 0 5px 10px rgba(0,0,0,0.1);\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".overview-boxes .box-topic{\\r\\n\"\r\n"
	       		+ "    			+ \"  font-size: 20px;\\r\\n\"\r\n"
	       		+ "    			+ \"  font-weight: 500;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".home-content .box .number{\\r\\n\"\r\n"
	       		+ "    			+ \"  display: inline-block;\\r\\n\"\r\n"
	       		+ "    			+ \"  font-size: 35px;\\r\\n\"\r\n"
	       		+ "    			+ \"  margin-top: -6px;\\r\\n\"\r\n"
	       		+ "    			+ \"  font-weight: 500;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".home-content .box .indicator{\\r\\n\"\r\n"
	       		+ "    			+ \"  display: flex;\\r\\n\"\r\n"
	       		+ "    			+ \"  align-items: center;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".home-content .box .indicator i{\\r\\n\"\r\n"
	       		+ "    			+ \"  height: 20px;\\r\\n\"\r\n"
	       		+ "    			+ \"  width: 20px;\\r\\n\"\r\n"
	       		+ "    			+ \"  background: #8FDACB;\\r\\n\"\r\n"
	       		+ "    			+ \"  line-height: 20px;\\r\\n\"\r\n"
	       		+ "    			+ \"  text-align: center;\\r\\n\"\r\n"
	       		+ "    			+ \"  border-radius: 50%;\\r\\n\"\r\n"
	       		+ "    			+ \"  color: #fff;\\r\\n\"\r\n"
	       		+ "    			+ \"  font-size: 20px;\\r\\n\"\r\n"
	       		+ "    			+ \"  margin-right: 5px;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".box .indicator i.down{\\r\\n\"\r\n"
	       		+ "    			+ \"  background: #e87d88;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".home-content .box .indicator .text{\\r\\n\"\r\n"
	       		+ "    			+ \"  font-size: 12px;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".home-content .box .cart{\\r\\n\"\r\n"
	       		+ "    			+ \"  display: inline-block;\\r\\n\"\r\n"
	       		+ "    			+ \"  font-size: 32px;\\r\\n\"\r\n"
	       		+ "    			+ \"  height: 50px;\\r\\n\"\r\n"
	       		+ "    			+ \"  width: 50px;\\r\\n\"\r\n"
	       		+ "    			+ \"  background: #cce5ff;\\r\\n\"\r\n"
	       		+ "    			+ \"  line-height: 50px;\\r\\n\"\r\n"
	       		+ "    			+ \"  text-align: center;\\r\\n\"\r\n"
	       		+ "    			+ \"  color: #66b0ff;\\r\\n\"\r\n"
	       		+ "    			+ \"  border-radius: 12px;\\r\\n\"\r\n"
	       		+ "    			+ \"  margin: -15px 0 0 6px;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".home-content .box .cart.two{\\r\\n\"\r\n"
	       		+ "    			+ \"   color: #2BD47D;\\r\\n\"\r\n"
	       		+ "    			+ \"   background: #C0F2D8;\\r\\n\"\r\n"
	       		+ "    			+ \" }\\r\\n\"\r\n"
	       		+ "    			+ \".home-content .box .cart.three{\\r\\n\"\r\n"
	       		+ "    			+ \"   color: #ffc233;\\r\\n\"\r\n"
	       		+ "    			+ \"   background: #ffe8b3;\\r\\n\"\r\n"
	       		+ "    			+ \" }\\r\\n\"\r\n"
	       		+ "    			+ \".home-content .box .cart.four{\\r\\n\"\r\n"
	       		+ "    			+ \"   color: #e05260;\\r\\n\"\r\n"
	       		+ "    			+ \"   background: #f7d4d7;\\r\\n\"\r\n"
	       		+ "    			+ \" }\\r\\n\"\r\n"
	       		+ "    			+ \".home-content .total-order{\\r\\n\"\r\n"
	       		+ "    			+ \"  font-size: 20px;\\r\\n\"\r\n"
	       		+ "    			+ \"  font-weight: 500;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".home-content .sales-boxes{\\r\\n\"\r\n"
	       		+ "    			+ \"  display: flex;\\r\\n\"\r\n"
	       		+ "    			+ \"  justify-content: space-between;\\r\\n\"\r\n"
	       		+ "    			+ \"  /* padding: 0 20px; */\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \"\\r\\n\"\r\n"
	       		+ "    			+ \"/* left box */\\r\\n\"\r\n"
	       		+ "    			+ \".home-content .sales-boxes .recent-sales{\\r\\n\"\r\n"
	       		+ "    			+ \"  width: 65%;\\r\\n\"\r\n"
	       		+ "    			+ \"  background: #fff;\\r\\n\"\r\n"
	       		+ "    			+ \"  padding: 20px 30px;\\r\\n\"\r\n"
	       		+ "    			+ \"  margin: 0 20px;\\r\\n\"\r\n"
	       		+ "    			+ \"  border-radius: 12px;\\r\\n\"\r\n"
	       		+ "    			+ \"  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".home-content .sales-boxes .sales-details{\\r\\n\"\r\n"
	       		+ "    			+ \"  display: flex;\\r\\n\"\r\n"
	       		+ "    			+ \"  align-items: center;\\r\\n\"\r\n"
	       		+ "    			+ \"  justify-content: space-between;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".sales-boxes .box .title{\\r\\n\"\r\n"
	       		+ "    			+ \"  font-size: 24px;\\r\\n\"\r\n"
	       		+ "    			+ \"  font-weight: 500;\\r\\n\"\r\n"
	       		+ "    			+ \"  /* margin-bottom: 10px; */\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".sales-boxes .sales-details li.topic{\\r\\n\"\r\n"
	       		+ "    			+ \"  font-size: 20px;\\r\\n\"\r\n"
	       		+ "    			+ \"  font-weight: 500;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".sales-boxes .sales-details li{\\r\\n\"\r\n"
	       		+ "    			+ \"  list-style: none;\\r\\n\"\r\n"
	       		+ "    			+ \"  margin: 8px 0;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".sales-boxes .sales-details li a{\\r\\n\"\r\n"
	       		+ "    			+ \"  font-size: 18px;\\r\\n\"\r\n"
	       		+ "    			+ \"  color: #333;\\r\\n\"\r\n"
	       		+ "    			+ \"  font-size: 400;\\r\\n\"\r\n"
	       		+ "    			+ \"  text-decoration: none;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".sales-boxes .box .button{\\r\\n\"\r\n"
	       		+ "    			+ \"  width: 100%;\\r\\n\"\r\n"
	       		+ "    			+ \"  display: flex;\\r\\n\"\r\n"
	       		+ "    			+ \"  justify-content: flex-end;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".sales-boxes .box .button a{\\r\\n\"\r\n"
	       		+ "    			+ \"  color: #fff;\\r\\n\"\r\n"
	       		+ "    			+ \"  background: #0A2558;\\r\\n\"\r\n"
	       		+ "    			+ \"  padding: 4px 12px;\\r\\n\"\r\n"
	       		+ "    			+ \"  font-size: 15px;\\r\\n\"\r\n"
	       		+ "    			+ \"  font-weight: 400;\\r\\n\"\r\n"
	       		+ "    			+ \"  border-radius: 4px;\\r\\n\"\r\n"
	       		+ "    			+ \"  text-decoration: none;\\r\\n\"\r\n"
	       		+ "    			+ \"  transition: all 0.3s ease;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".sales-boxes .box .button a:hover{\\r\\n\"\r\n"
	       		+ "    			+ \"  background:  #0d3073;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \"\\r\\n\"\r\n"
	       		+ "    			+ \"/* Right box */\\r\\n\"\r\n"
	       		+ "    			+ \".home-content .sales-boxes .top-sales{\\r\\n\"\r\n"
	       		+ "    			+ \"  width: 35%;\\r\\n\"\r\n"
	       		+ "    			+ \"  background: #fff;\\r\\n\"\r\n"
	       		+ "    			+ \"  padding: 20px 30px;\\r\\n\"\r\n"
	       		+ "    			+ \"  margin: 0 20px 0 0;\\r\\n\"\r\n"
	       		+ "    			+ \"  border-radius: 12px;\\r\\n\"\r\n"
	       		+ "    			+ \"  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".sales-boxes .top-sales li{\\r\\n\"\r\n"
	       		+ "    			+ \"  display: flex;\\r\\n\"\r\n"
	       		+ "    			+ \"  align-items: center;\\r\\n\"\r\n"
	       		+ "    			+ \"  justify-content: space-between;\\r\\n\"\r\n"
	       		+ "    			+ \"  margin: 10px 0;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".sales-boxes .top-sales li a img{\\r\\n\"\r\n"
	       		+ "    			+ \"  height: 40px;\\r\\n\"\r\n"
	       		+ "    			+ \"  width: 40px;\\r\\n\"\r\n"
	       		+ "    			+ \"  object-fit: cover;\\r\\n\"\r\n"
	       		+ "    			+ \"  border-radius: 12px;\\r\\n\"\r\n"
	       		+ "    			+ \"  margin-right: 10px;\\r\\n\"\r\n"
	       		+ "    			+ \"  background: #333;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".sales-boxes .top-sales li a{\\r\\n\"\r\n"
	       		+ "    			+ \"  display: flex;\\r\\n\"\r\n"
	       		+ "    			+ \"  align-items: center;\\r\\n\"\r\n"
	       		+ "    			+ \"  text-decoration: none;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".sales-boxes .top-sales li .product,\\r\\n\"\r\n"
	       		+ "    			+ \".price{\\r\\n\"\r\n"
	       		+ "    			+ \"  font-size: 17px;\\r\\n\"\r\n"
	       		+ "    			+ \"  font-weight: 400;\\r\\n\"\r\n"
	       		+ "    			+ \"  color: #333;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \"/* Responsive Media Query */\\r\\n\"\r\n"
	       		+ "    			+ \"@media (max-width: 1240px) {\\r\\n\"\r\n"
	       		+ "    			+ \"  .sidebar{\\r\\n\"\r\n"
	       		+ "    			+ \"    width: 60px;\\r\\n\"\r\n"
	       		+ "    			+ \"  }\\r\\n\"\r\n"
	       		+ "    			+ \"  .sidebar.active{\\r\\n\"\r\n"
	       		+ "    			+ \"    width: 220px;\\r\\n\"\r\n"
	       		+ "    			+ \"  }\\r\\n\"\r\n"
	       		+ "    			+ \"  .home-section{\\r\\n\"\r\n"
	       		+ "    			+ \"    width: calc(100% - 60px);\\r\\n\"\r\n"
	       		+ "    			+ \"    left: 60px;\\r\\n\"\r\n"
	       		+ "    			+ \"  }\\r\\n\"\r\n"
	       		+ "    			+ \"  .sidebar.active ~ .home-section{\\r\\n\"\r\n"
	       		+ "    			+ \"    /* width: calc(100% - 220px); */\\r\\n\"\r\n"
	       		+ "    			+ \"    overflow: hidden;\\r\\n\"\r\n"
	       		+ "    			+ \"    left: 220px;\\r\\n\"\r\n"
	       		+ "    			+ \"  }\\r\\n\"\r\n"
	       		+ "    			+ \"  .home-section nav{\\r\\n\"\r\n"
	       		+ "    			+ \"    width: calc(100% - 60px);\\r\\n\"\r\n"
	       		+ "    			+ \"    left: 60px;\\r\\n\"\r\n"
	       		+ "    			+ \"  }\\r\\n\"\r\n"
	       		+ "    			+ \"  .sidebar.active ~ .home-section nav{\\r\\n\"\r\n"
	       		+ "    			+ \"    width: calc(100% - 220px);\\r\\n\"\r\n"
	       		+ "    			+ \"    left: 220px;\\r\\n\"\r\n"
	       		+ "    			+ \"  }\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \"@media (max-width: 1150px) {\\r\\n\"\r\n"
	       		+ "    			+ \"  .home-content .sales-boxes{\\r\\n\"\r\n"
	       		+ "    			+ \"    flex-direction: column;\\r\\n\"\r\n"
	       		+ "    			+ \"  }\\r\\n\"\r\n"
	       		+ "    			+ \"  .home-content .sales-boxes .box{\\r\\n\"\r\n"
	       		+ "    			+ \"    width: 100%;\\r\\n\"\r\n"
	       		+ "    			+ \"    overflow-x: scroll;\\r\\n\"\r\n"
	       		+ "    			+ \"    margin-bottom: 30px;\\r\\n\"\r\n"
	       		+ "    			+ \"  }\\r\\n\"\r\n"
	       		+ "    			+ \"  .home-content .sales-boxes .top-sales{\\r\\n\"\r\n"
	       		+ "    			+ \"    margin: 0;\\r\\n\"\r\n"
	       		+ "    			+ \"  }\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \"@media (max-width: 1000px) {\\r\\n\"\r\n"
	       		+ "    			+ \"  .overview-boxes .box{\\r\\n\"\r\n"
	       		+ "    			+ \"    width: calc(100% / 2 - 15px);\\r\\n\"\r\n"
	       		+ "    			+ \"    margin-bottom: 15px;\\r\\n\"\r\n"
	       		+ "    			+ \"  }\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \"@media (max-width: 700px) {\\r\\n\"\r\n"
	       		+ "    			+ \"  nav .sidebar-button .dashboard,\\r\\n\"\r\n"
	       		+ "    			+ \"  nav .profile-details .admin_name,\\r\\n\"\r\n"
	       		+ "    			+ \"  nav .profile-details i{\\r\\n\"\r\n"
	       		+ "    			+ \"    display: none;\\r\\n\"\r\n"
	       		+ "    			+ \"  }\\r\\n\"\r\n"
	       		+ "    			+ \"  .home-section nav .profile-details{\\r\\n\"\r\n"
	       		+ "    			+ \"    height: 50px;\\r\\n\"\r\n"
	       		+ "    			+ \"    min-width: 40px;\\r\\n\"\r\n"
	       		+ "    			+ \"  }\\r\\n\"\r\n"
	       		+ "    			+ \"  .home-content .sales-boxes .sales-details{\\r\\n\"\r\n"
	       		+ "    			+ \"    width: 560px;\\r\\n\"\r\n"
	       		+ "    			+ \"  }\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \"@media (max-width: 550px) {\\r\\n\"\r\n"
	       		+ "    			+ \"  .overview-boxes .box{\\r\\n\"\r\n"
	       		+ "    			+ \"    width: 100%;\\r\\n\"\r\n"
	       		+ "    			+ \"    margin-bottom: 15px;\\r\\n\"\r\n"
	       		+ "    			+ \"  }\\r\\n\"\r\n"
	       		+ "    			+ \"  .sidebar.active ~ .home-section nav .profile-details{\\r\\n\"\r\n"
	       		+ "    			+ \"    display: none;\\r\\n\"\r\n"
	       		+ "    			+ \"  }\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \" .btn {\\r\\n\"\r\n"
	       		+ "    			+ \"    width: 85px;\\r\\n\"\r\n"
	       		+ "    			+ \"    background-color: #5995fd;\\r\\n\"\r\n"
	       		+ "    			+ \"    border: none;\\r\\n\"\r\n"
	       		+ "    			+ \"    outline: none;\\r\\n\"\r\n"
	       		+ "    			+ \"    height: 20px;\\r\\n\"\r\n"
	       		+ "    			+ \"    border-radius: 4px;\\r\\n\"\r\n"
	       		+ "    			+ \"    color: #fff;\\r\\n\"\r\n"
	       		+ "    			+ \"    text-transform: normal;\\r\\n\"\r\n"
	       		+ "    			+ \"    font-weight: 200;\\r\\n\"\r\n"
	       		+ "    			+ \"    margin: 10px 0;\\r\\n\"\r\n"
	       		+ "    			+ \"    cursor: pointer;\\r\\n\"\r\n"
	       		+ "    			+ \"    transition: 0.5s;\\r\\n\"\r\n"
	       		+ "    			+ \"    margin-top: 4px;\\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \" .btn1{float: right} {\\r\\n\"\r\n"
	       		+ "    			+ \"    \\r\\n\"\r\n"
	       		+ "    			+ \"    \\r\\n\"\r\n"
	       		+ "    			+ \"}\\r\\n\"\r\n"
	       		+ "    			+ \".btn1{\\r\\n\"\r\n"
	       		+ "    			+ \"width: 150px;\\r\\n\"\r\n"
	       		+ "    			+ \"  background-color: #5995fd;\\r\\n\"\r\n"
	       		+ "    			+ \"  border: none;\\r\\n\"\r\n"
	       		+ "    			+ \"  outline: none;\\r\\n\"\r\n"
	       		+ "    			+ \"  height: 28px;\\r\\n\"\r\n"
	       		+ "    			+ \"  border-radius: 49px;\\r\\n\"\r\n"
	       		+ "    			+ \"  color: #fff;\\r\\n\"\r\n"
	       		+ "    			+ \"  text-transform: uppercase;\\r\\n\"\r\n"
	       		+ "    			+ \"  font-weight: 600;\\r\\n\"\r\n"
	       		+ "    			+ \"  margin: 10px 0;\\r\\n\"\r\n"
	       		+ "    			+ \"  cursor: pointer;\\r\\n\"\r\n"
	       		+ "    			+ \"  transition: 0.5s;\\r\\n\"\r\n"
	       		+ "    			+ \"  }\\r\\n\"\r\n"
	       		+ "    			+ \"  </style>\\r\\n\"\r\n"
	       		+ "    			+ \"    <meta charset=\\\"UTF-8\\\">\\r\\n\"\r\n"
	       		+ "    			+ \"    <!--<title> Responsiive Admin Dashboard | CodingLab </title>-->\\r\\n\"\r\n"
	       		+ "    			+ \"    <link rel=\\\"stylesheet\\\" href=\\\"style.css\\\">\\r\\n\"\r\n"
	       		+ "    			+ \"    <!-- Boxicons CDN Link -->\\r\\n\"\r\n"
	       		+ "    			+ \"    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>\\r\\n\"\r\n"
	       		+ "    			+ \"     <meta name=\\\"viewport\\\" content=\\\"width=device-width, initial-scale=1.0\\\">\\r\\n\"\r\n"
	       		+ "    			+ \"   </head>\\r\\n\"\r\n"
	       		+ "    			+ \"<body>\\r\\n\"\r\n"
	       		+ "    			+ \"  <div class=\\\"sidebar\\\">\\r\\n\"\r\n"
	       		+ "    			+ \"    <div class=\\\"logo-details\\\">\\r\\n\"\r\n"
	       		+ "    			+ \"       <i class='bx bxs-user-check' ></i>\\r\\n\"\r\n"
	       		+ "    			+ \"      <span class=\\\"logo_name\\\">Admin</span>\\r\\n\"\r\n"
	       		+ "    			+ \"    </div>\\r\\n\"\r\n"
	       		+ "    			+ \"    <hr>\\r\\n\"\r\n"
	       		+ "    			+ \"      <ul class=\\\"nav-links\\\">\\r\\n\"\r\n"
	       		+ "    			+ \"        \\r\\n\"\r\n"
	       		+ "    			+ \"        <li>\\r\\n\"\r\n"
	       		+ "    			+ \"          <a href=\\\"InsertProduct.jsp\\\">\\r\\n\"\r\n"
	       		+ "    			+ \"            <i class='bx bxs-cart-add'></i>\\r\\n\"\r\n"
	       		+ "    			+ \"            <span class=\\\"links_name\\\">Insert Products</span>\\r\\n\"\r\n"
	       		+ "    			+ \"          </a>\\r\\n\"\r\n"
	       		+ "    			+ \"        </li>\\r\\n\"\r\n"
	       		+ "    			+ \"        <li>\\r\\n\"\r\n"
	       		+ "    			+ \"          <a href=\\\"Delete.jsp\\\">\\r\\n\"\r\n"
	       		+ "    			+ \"            <i class='bx bxs-chevrons-up'></i>\\r\\n\"\r\n"
	       		+ "    			+ \"            <span class=\\\"links_name\\\">Update Doctors</span>\\r\\n\"\r\n"
	       		+ "    			+ \"          </a>\\r\\n\"\r\n"
	       		+ "    			+ \"        </li>\\r\\n\"\r\n"
	       		+ "    			+ \"        \\r\\n\"\r\n"
	       		+ "    			+ \"        <li>\\r\\n\"\r\n"
	       		+ "    			+ \"          <a href=\\\"InsertDoctor.jsp\\\">\\r\\n\"\r\n"
	       		+ "    			+ \"            <i class='bx bx-plus-medical'></i>\\r\\n\"\r\n"
	       		+ "    			+ \"            <span class=\\\"links_name\\\">Insert Doctors</span>\\r\\n\"\r\n"
	       		+ "    			+ \"          </a>\\r\\n\"\r\n"
	       		+ "    			+ \"        </li>\\r\\n\"\r\n"
	       		+ "    			+ \"        <li>\\r\\n\"\r\n"
	       		+ "    			+ \"          <a href=\\\"#\\\">\\r\\n\"\r\n"
	       		+ "    			+ \"            <i class='bx bx-donate-heart'></i>\\r\\n\"\r\n"
	       		+ "    			+ \"            <span class=\\\"links_name\\\">View Your Doctor</span>\\r\\n\"\r\n"
	       		+ "    			+ \"          </a>\\r\\n\"\r\n"
	       		+ "    			+ \"        </li>\\r\\n\"\r\n"
	       		+ "    			+ \"         <li>\\r\\n\"\r\n"
	       		+ "    			+ \"          <a href=\\\"#\\\">\\r\\n\"\r\n"
	       		+ "    			+ \"            <i class='bx bxs-shopping-bags'></i>\\r\\n\"\r\n"
	       		+ "    			+ \"            <span class=\\\"links_name\\\">View Products</span>\\r\\n\"\r\n"
	       		+ "    			+ \"          </a>\\r\\n\"\r\n"
	       		+ "    			+ \"        <li class=\\\"log_out\\\">\\r\\n\"\r\n"
	       		+ "    			+ \"          <a href=\\\"#\\\">\\r\\n\"\r\n"
	       		+ "    			+ \"            <i class='bx bx-log-out'></i>\\r\\n\"\r\n"
	       		+ "    			+ \"            <span class=\\\"links_name\\\">Log out</span>\\r\\n\"\r\n"
	       		+ "    			+ \"          </a>\\r\\n\"\r\n"
	       		+ "    			+ \"        </li>\\r\\n\"\r\n"
	       		+ "    			+ \"         <li>\\r\\n\"\r\n"
	       		+ "    			+ \"          <a href=\\\"#\\\">\\r\\n\"\r\n"
	       		+ "    			+ \"            <i class='bx bx-help-circle' ></i>\\r\\n\"\r\n"
	       		+ "    			+ \"            <span class=\\\"links_name\\\">Help</span>\\r\\n\"\r\n"
	       		+ "    			+ \"          </a>\\r\\n\"\r\n"
	       		+ "    			+ \"        </li>\\r\\n\"\r\n"
	       		+ "    			+ \"      </ul>\\r\\n\"\r\n"
	       		+ "    			+ \"  </div>\\r\\n\"\r\n"
	       		+ "    			+ \"  <section class=\\\"home-section\\\">\\r\\n\"\r\n"
	       		+ "    			+ \"  <form action=\\\"\\\" method=\\\"get\\\">\\r\\n\"\r\n"
	       		+ "    			+ \"    <nav>\\r\\n\"\r\n"
	       		+ "    			+ \"      <div class=\\\"sidebar-button\\\">\\r\\n\"\r\n"
	       		+ "    			+ \"        <i class='bx bx-menu sidebarBtn'></i>\\r\\n\"\r\n"
	       		+ "    			+ \"        <span class=\\\"dashboard\\\">Dashboard</span>\\r\\n\"\r\n"
	       		+ "    			+ \"      </div>\\r\\n\"\r\n"
	       		+ "    			+ \"      <div class=\\\"search-box\\\">\\r\\n\"\r\n"
	       		+ "    			+ \"        <input type=\\\"text\\\" name = \\\"q\\\" placeholder=\\\"Enter Doctor's Name\\\">\\r\\n\"\r\n"
	       		+ "    			+ \"        <i class='bx bx-search' ></i>\\r\\n\"\r\n"
	       		+ "    			+ \"      </div>\\r\\n\"\r\n"
	       		+ "    			+ \"    </nav>\\r\\n\"\r\n"
	       		+ "    			+ \"    </form>\\r\\n\"\r\n"
	       		+ "    			+ \"    \\r\\n\"\r\n"
	       		+ "    			+ \"    <div class=\\\"home-content\\\">\\r\\n\"\r\n"
	       		+ "    			+ \"      <div class=\\\"invoice-box\\\">\\r\\n\"\r\n"
	       		+ "    			+ \"        <table cellpadding=\\\"0\\\" cellspacing=\\\"0\\\" cellpadding=\\\"0\\\" cellspacing=\\\"0\\\">\\r\\n\"\r\n"
	       		+ "    			+ \"         <a href =\\\"InsertProduct.jsp\\\" \\\"><button class =\\\"btn1\\\">Add Products <i class='bx bxs-file-plus'></i></button></a>\\r\\n\"\r\n"
	       		+ "    			+ \"        <tr class=\\\"heading\\\">\\r\\n\"\r\n"
	       		+ "    			+ \"            <td>Medicine ID</td>\\r\\n\"\r\n"
	       		+ "    			+ \"  \\r\\n\"\r\n"
	       		+ "    			+ \"            <td> Name </td>\\r\\n\"\r\n"
	       		+ "    			+ \"            \\r\\n\"\r\n"
	       		+ "    			+ \"            <td> Price </td>\\r\\n\"\r\n"
	       		+ "    			+ \"            \\r\\n\"\r\n"
	       		+ "    			+ \"            <td>Quantity</td>\\r\\n\"\r\n"
	       		+ "    			+ \"            \\r\\n\"\r\n"
	       		+ "    			+ \"            <td>Action</td>\\r\\n\"\r\n"
	       		+ "    			+ \"          </tr>\"");
	        for(int i =0;i<ck.length;i++)
	        {
	        	q="select * from products where id = "+ck[i].getName()+"";
	        	pst = con.prepareStatement(q);
	        	rs=pst.executeQuery();
	        	while(rs.next())
	        	{
	        	pw.print(" <tr class=\"item\">\r\n"
	    				+ "            <td><"+rs.getString(1)+"</td>\r\n"
	    				+ "  \r\n"
	    				+ "            <td><"+rs.getString(2)+"</td>\r\n"
	    				+ "  \r\n"
	    				+ "            <td><"+rs.getString(3)+"</td>\r\n"
	    				+ "  \r\n"
	    				+ "            <td><"+rs.getString(4)+"</td>\r\n"
	    				+ "  \r\n"
	    				+ "            <td class =\"text-center\">\r\n"
	    				+ "            <a href ='ViewCartItems?ItemId="+rs.getInt(1)+"'>Add to cart</a>"
	    				
	    				+ "          </td>\r\n"
	    				+ "          </tr>");
	    	}
		}
	    } 
	    catch (ClassNotFoundException e) {
	        // TODO Auto-generated catch block
	        e.printStackTrace();
	    }
	     catch (SQLException e) {
	        // TODO Auto-generated catch block
	        e.printStackTrace();
	    }
	}

}
